[project]
name = "smart_contract"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "W:\\FractionalizerDemo\\src\\smart_contract\\.\\.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.fractionalizer-rea]
path = "contracts/fractionalizer-rea.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
